### ISSUE TITLE
Only works on node 16, doesn't work versions above

### ISSUE THREAD

**Issue by m41w4r3exe** [LibreScore/webmscore#12]
Thank you bazilions for the amazing library! 

For anyone facing similar issue: Webscore.ready throws error below for any node versions above 16, like 18.x.x or 20.x.x.

`node:internal/deps/undici/undici:11372
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Volumes/Zamazingo/repos/musescore-mscxs/node_modules/webmscore/webmscore.lib.wasm
    at Object.fetch (node:internal/deps/undici/undici:11372:11) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:775:36)
      at new _Request (node:internal/deps/undici/undici:5055:25)
      at fetch2 (node:internal/deps/undici/undici:9195:25)
      at Object.fetch (node:internal/deps/undici/undici:11370:18)
      at fetch (node:internal/process/pre_execution:282:25)
      at instantiateAsync (/Volumes/Zamazingo/repos/musescore-mscxs/node_modules/webmscore/webmscore.nodejs.cjs:63:70039)
      at createWasm (/Volumes/Zamazingo/repos/musescore-mscxs/node_modules/webmscore/webmscore.nodejs.cjs:63:70648)
      at /Volumes/Zamazingo/repos/musescore-mscxs/node_modules/webmscore/webmscore.nodejs.cjs:63:212265
      at Object.<anonymous> (/Volumes/Zamazingo/repos/musescore-mscxs/node_modules/webmscore/webmscore.nodejs.cjs:96:23)
      at Module._compile (node:internal/modules/cjs/loader:1241:14) {
    code: 'ERR_INVALID_URL',
    input: '/Volumes/Zamazingo/repos/musescore-mscxs/node_modules/webmscore/webmscore.lib.wasm'
  }
}

Node.js v20.8.1`

**Comment by PeterNjeim** [comment]
Caused by: https://github.com/nodejs/undici/issues/1857#issuecomment-1793572098

Related: #10, https://github.com/LibreScore/dl-librescore/issues/16
